// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pfldropzugtmgzdjezby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmbGRyb3B6dWd0bWd6ZGplemJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxODU0NzAsImV4cCI6MjA3MTc2MTQ3MH0.YZX2ZkKbeteJ8XAqYwPtbUJ6rYsS_qwBJksKKOhSIzM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});